#if !canImport(ObjectiveC)
import XCTest

extension CommonMarkBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonMarkBuilderTests = [
        ("testCommonMarkBuilder", testCommonMarkBuilder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommonMarkBuilderTests.__allTests__CommonMarkBuilderTests),
    ]
}
#endif
