#if !canImport(ObjectiveC)
import XCTest

extension CommonMarkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonMarkTests = [
        ("testCommonMarkVersion", testCommonMarkVersion),
    ]
}

extension DocumentCreationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentCreationTests = [
        ("testDocumentCreation", testDocumentCreation),
    ]
}

extension DocumentParsingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentParsingTests = [
        ("testDocumentParsing", testDocumentParsing),
        ("testInvalidRange", testInvalidRange),
    ]
}

extension DocumentRenderingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentRenderingTests = [
        ("testDocumentCommonMarkRendering", testDocumentCommonMarkRendering),
        ("testDocumentHTMLRendering", testDocumentHTMLRendering),
        ("testDocumentLaTeXRendering", testDocumentLaTeXRendering),
        ("testDocumentManpageRendering", testDocumentManpageRendering),
        ("testDocumentXMLRendering", testDocumentXMLRendering),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommonMarkTests.__allTests__CommonMarkTests),
        testCase(DocumentCreationTests.__allTests__DocumentCreationTests),
        testCase(DocumentParsingTests.__allTests__DocumentParsingTests),
        testCase(DocumentRenderingTests.__allTests__DocumentRenderingTests),
    ]
}
#endif
